[tool.poetry]
name = "python-poetry"
version = "1.0.0"
description = "A Python Docker image with Poetry installed and ready to use."
authors = ["Max Pfeiffer <max@maxpfeiffer.ch>"]
license = "MIT"

[tool.poetry.dependencies]
python = "3.9.*"
python-dotenv = "0.21.0"

[tool.poetry.dev-dependencies]
pylint = "2.15.3"
pytest = "7.1.3"
pytest-cov = "4.0.0"
coverage = "6.5.0"
docker = "6.0.0"
requests = "2.28.1"
black = "22.10.0"
pre-commit = "2.20.0"
semver = "2.13.0"

# https://docs.pytest.org/en/latest/reference/customize.html
[tool.pytest.ini_options]
testpaths = [
    "tests",
]

# https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html#configuration-via-a-file
[tool.black]
line-length = 80
target-version = ["py39"]

[tool.pylint.main]
errors-only = true
recursive = "y"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
